GET http://localhost:1337 

###
POST http://localhost:1337/user/register
Content-Type: application/json

{
    "email": "tiendatpot12@gmail.com",
    "password": "abc1232"
}

###
GET http://localhost:1337/user/getAllUsers

###
POST http://localhost:1337/user/refresh-token

###
POST http://localhost:1337/user/login
Content-Type: application/json

{
    "email": "tiendatpot12@gmail.com",
    "password": "abc1232"
}

###
POST http://localhost:1337/user/logout


###
GET http://localhost:1337/user/getlists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFlNzA5MDQ0NjE2OTlkYjE3MDUzNDAiLCJpYXQiOjE3MDU5MzY5MjQsImV4cCI6MTcwNTkzNjkzNH0.R4jYhC7pEjzH3Dx890Z5_iNT4Bkq7cp65rvmO6mOjyA